FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:20-alpine AS dev
WORKDIR /app
ENV NODE_ENV=development
ENV VUE_APP_PREVIEW=true
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE 8000
CMD ["yarn", "serve"]